aa

diff --git a/.github/terraform.yml b/.github/terraform.yml
--- a/.github/terraform.yml
+++ b/.github/terraform.yml
@@ -13,11 +13,11 @@ on:
       - terraform/**
 
 env:
- AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
- AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
- BUCKET_TF_STATE: ${{ secrets.BUCKET_TF_STATE }}
- AWS_REGION: us-east-1
- EKS_CLUSTER: vprofile-eks             
+  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
+  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+  BUCKET_TF_STATE: ${{ secrets.BUCKET_TF_STATE }}
+  AWS_REGION: us-east-1
+  EKS_CLUSTER: vprofile-eks             
 
 jobs:
   terraform:
@@ -30,10 +30,10 @@ jobs:
     steps:
       - name: Checkout source code 
         uses: actions/checkout@v4
+
       - name: setup terraform
         uses: hashicorp/setup-terraform@v2
-        #with:
-          #terraform_version: 1.6.3
+
       - name: Terraform init
         id: init
         run: terraform init -backend-config="bucket=$BUCKET_TF_STATE"
@@ -53,6 +53,6 @@ jobs:
 
       - name: Terraform plan status
         if: steps.plan.outcome == 'failure'
-        run: exit 1
-
-  
+        run: |
+          echo "Terraform plan failed."
+          exit 1
